require 'json'
require 'httparty'
require 'active_support/core_ext'

require './riot_api/champion'
require './riot_api/game'
require './riot_api/client'
require './riot_api/aggregated_stat'
require './riot_api/mastery_page'
require './riot_api/rune'
require './riot_api/talent'
require './riot_api/player_stat_summary'
require './riot_api/rune_page'
require './riot_api/summoner'